// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:dndman_app/dnd/dnd.dart' as prefix1;
import 'package:dndman_app/dnd/races.dart' as prefix2;
import 'package:dndman_app/form_generator/annotations/hide.dart' as prefix3;
import 'package:dndman_app/form_generator/annotations/reflector.dart'
    as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.ClassReflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'DNDCharacter',
            r'.DNDCharacter',
            7,
            0,
            const prefix0.ClassReflector(),
            const <int>[0, 1, 2, 3, 4, 5, 6, 7, 22],
            const <int>[
              23,
              24,
              25,
              26,
              27,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21
            ],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => (
                      {playerName = "Enter Player Name",
                      characterName = "Enter Character Name",
                      armourClass = 0,
                      initiativeBonus = 0,
                      hitDice = const prefix1.DiceRoll()}) =>
                  b
                      ? prefix1.DNDCharacter(
                          armourClass: armourClass,
                          characterName: characterName,
                          hitDice: hitDice,
                          initiativeBonus: initiativeBonus,
                          playerName: playerName)
                      : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[prefix0.reflector],
            null),
        r.NonGenericClassMirrorImpl(
            r'DiceRoll',
            r'.DiceRoll',
            7,
            1,
            const prefix0.ClassReflector(),
            const <int>[8, 9, 10, 31, 32],
            const <int>[23, 24, 25, 26, 27, 28, 29, 30],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({max = 20, maxTryCount = 1, value = 20}) => b
                  ? prefix1.DiceRoll(
                      max: max, maxTryCount: maxTryCount, value: value)
                  : null,
              r'copy': (bool b) => (other, value) =>
                  b ? prefix1.DiceRoll.copy(other, value) : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[prefix0.reflector],
            null),
        r.NonGenericClassMirrorImpl(
            r'Race',
            r'.Race',
            7,
            2,
            const prefix0.ClassReflector(),
            const <int>[33],
            const <int>[23, 24, 25, 26, 27],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix2.Race() : null},
            -1,
            -1,
            const <int>[-1],
            const <Object>[prefix0.reflector],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'playerName', 33797, 0,
            const prefix0.ClassReflector(), -1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'characterName', 33797, 0,
            const prefix0.ClassReflector(), -1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'armourClass', 33797, 0,
            const prefix0.ClassReflector(), -1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'initiativeBonus', 33797, 0,
            const prefix0.ClassReflector(), -1, -1, -1, null, const []),
        r.VariableMirrorImpl(
            r'speedInFeet',
            33797,
            0,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix3.FormHidden()]),
        r.VariableMirrorImpl(
            r'maxHitPoints',
            33797,
            0,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix3.FormHidden()]),
        r.VariableMirrorImpl(
            r'currentHitPoints',
            32773,
            0,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix3.FormHidden()]),
        r.VariableMirrorImpl(r'hitDice', 33797, 0,
            const prefix0.ClassReflector(), 1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'max', 33797, 1, const prefix0.ClassReflector(),
            -1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'maxTryCount', 33797, 1,
            const prefix0.ClassReflector(), -1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'value', 33797, 1, const prefix0.ClassReflector(),
            -1, -1, -1, null, const []),
        r.ImplicitGetterMirrorImpl(const prefix0.ClassReflector(), 0, 11),
        r.ImplicitGetterMirrorImpl(const prefix0.ClassReflector(), 1, 12),
        r.ImplicitGetterMirrorImpl(const prefix0.ClassReflector(), 2, 13),
        r.ImplicitGetterMirrorImpl(const prefix0.ClassReflector(), 3, 14),
        r.ImplicitGetterMirrorImpl(const prefix0.ClassReflector(), 4, 15),
        r.ImplicitSetterMirrorImpl(const prefix0.ClassReflector(), 4, 16),
        r.ImplicitGetterMirrorImpl(const prefix0.ClassReflector(), 5, 17),
        r.ImplicitSetterMirrorImpl(const prefix0.ClassReflector(), 5, 18),
        r.ImplicitGetterMirrorImpl(const prefix0.ClassReflector(), 6, 19),
        r.ImplicitSetterMirrorImpl(const prefix0.ClassReflector(), 6, 20),
        r.ImplicitGetterMirrorImpl(const prefix0.ClassReflector(), 7, 21),
        r.MethodMirrorImpl(
            r'',
            0,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[0, 1, 2, 3, 4],
            const prefix0.ClassReflector(),
            const []),
        r.MethodMirrorImpl(r'==', 131074, -1, -1, -1, -1, null, const <int>[8],
            const prefix0.ClassReflector(), const []),
        r.MethodMirrorImpl(r'toString', 131074, -1, -1, -1, -1, null,
            const <int>[], const prefix0.ClassReflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, -1, -1, -1, -1, null,
            const <int>[9], const prefix0.ClassReflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 131075, -1, -1, -1, -1, null,
            const <int>[], const prefix0.ClassReflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, -1, -1, -1, -1, null,
            const <int>[], const prefix0.ClassReflector(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.ClassReflector(), 8, 28),
        r.ImplicitGetterMirrorImpl(const prefix0.ClassReflector(), 9, 29),
        r.ImplicitGetterMirrorImpl(const prefix0.ClassReflector(), 10, 30),
        r.MethodMirrorImpl(r'', 128, 1, -1, -1, -1, null,
            const <int>[10, 11, 12], const prefix0.ClassReflector(), const []),
        r.MethodMirrorImpl(r'copy', 1, 1, -1, -1, -1, null, const <int>[13, 14],
            const prefix0.ClassReflector(), const []),
        r.MethodMirrorImpl(r'', 64, 2, -1, -1, -1, null, const <int>[],
            const prefix0.ClassReflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'playerName',
            48134,
            22,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            "Enter Player Name",
            #playerName),
        r.ParameterMirrorImpl(
            r'characterName',
            48134,
            22,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            "Enter Character Name",
            #characterName),
        r.ParameterMirrorImpl(
            r'armourClass',
            48134,
            22,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            0,
            #armourClass),
        r.ParameterMirrorImpl(
            r'initiativeBonus',
            48134,
            22,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            0,
            #initiativeBonus),
        r.ParameterMirrorImpl(
            r'hitDice',
            48134,
            22,
            const prefix0.ClassReflector(),
            1,
            -1,
            -1,
            null,
            const [],
            const prefix1.DiceRoll(),
            #hitDice),
        r.ParameterMirrorImpl(
            r'_speedInFeet',
            32870,
            16,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_maxHitPoints',
            32870,
            18,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_currentHitPoints',
            32870,
            20,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            23,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            25,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r'max', 48134, 31, const prefix0.ClassReflector(),
            -1, -1, -1, null, const [], 20, #max),
        r.ParameterMirrorImpl(
            r'maxTryCount',
            48134,
            31,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            1,
            #maxTryCount),
        r.ParameterMirrorImpl(
            r'value',
            48134,
            31,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            20,
            #value),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            32,
            const prefix0.ClassReflector(),
            1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'value',
            32774,
            32,
            const prefix0.ClassReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null)
      ],
      <Type>[prefix1.DNDCharacter, prefix1.DiceRoll, prefix2.Race],
      3,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'playerName': (dynamic instance) => instance.playerName,
        r'characterName': (dynamic instance) => instance.characterName,
        r'armourClass': (dynamic instance) => instance.armourClass,
        r'initiativeBonus': (dynamic instance) => instance.initiativeBonus,
        r'speedInFeet': (dynamic instance) => instance.speedInFeet,
        r'maxHitPoints': (dynamic instance) => instance.maxHitPoints,
        r'currentHitPoints': (dynamic instance) => instance.currentHitPoints,
        r'hitDice': (dynamic instance) => instance.hitDice,
        r'max': (dynamic instance) => instance.max,
        r'maxTryCount': (dynamic instance) => instance.maxTryCount,
        r'value': (dynamic instance) => instance.value
      },
      {
        r'speedInFeet=': (dynamic instance, value) =>
            instance.speedInFeet = value,
        r'maxHitPoints=': (dynamic instance, value) =>
            instance.maxHitPoints = value,
        r'currentHitPoints=': (dynamic instance, value) =>
            instance.currentHitPoints = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
